### ISSUE TITLE
New Post Error with Wrong characters

### ISSUE THREAD

**Issue by Alehap** [xfrocks/bdApi#10]
Hello,
I've trouble when use API to post a message with some broken character such as "Hắn phóng ngựa tiến về phía Hàn Đ��"
It's show up:
Array
(
    [errors] => Array
        (
            [0] => Xin mời nhập vào đúng nội dung.
        )

```
[system_info] => Array
    (
        [visitor_id] => 1
        [time] => 1458285458
    )
```

)

But if I use this message and post directly to thread, it's successfully without errors.

**Comment by daohoangson** [comment]
Can you try to reproduce the test with `curl` command and post the full command here?

**Comment by Alehap** [comment]
Hello Sơn,
This is the full content of post data I've used for curl : 

Please see at the attachment cause of very long text.
[curl_BDAPI_xen.txt](https://github.com/xfrocks/bdApi/files/179309/curl_BDAPI_xen.txt)

The broken text is the end of message (Lưu tinh chuy cắm vào giữa lưng Diêm Hành. Cũng may Diêm Hành cảm nhận được nguy hiểm, lệnh chiến mã đột ngột tăng tốc, thân người hơi ngả về phía trước nên Lưu tinh chuy mới không cắm sâu vào. Cho dù là như thế, cảm giác bị đánh trúng cũng chẳng dễ chịu gì. Diêm Hành nằm trên lưng ngựa, phun ra một ngụm máu tươi, cây �)

And I've got response:
{"errors":["Xin m\u1eddi nh\u1eadp v\u00e0o \u0111\u00fang n\u1ed9i dung."],"system_info":{"visitor_id":1,"time":1458291519}}

**Comment by daohoangson** [comment]
I have tracked this issue and this was caused by this piece of code in `XenForo_Input`

```
    protected static function _doClean($filterName, array $filterOptions, $data, $defaultData)
    {
        switch ($filterName)
        {
            case self::STRING:
                $data = is_scalar($data) ? strval($data) : $defaultData;
                if (strlen($data) && !preg_match('/./u', $data))
                {
                    $data = $defaultData;
                }

                $data = self::cleanString($data);

                if (empty($filterOptions['noTrim']))
                {
                    $data = trim($data);
                }
            break;
```

Basically your input contains an invalid unicode character and this method detects it and nullifies the entire string (this is done for security reason). Your best bet is to modify your code and validate data before submitting to XenForo.
