### ISSUE TITLE
How to order thread by first post edit

### ISSUE THREAD

**Issue by kenthd** [xfrocks/bdApi#100]
Hi dev, 
bdApi really great.

bdApi support thread types order by: thread_create_date, thread_create_date_reverse, thread_update_date, thread_update_date_reverse, thread_view_count, thread_view_count_reverse.

Now I want to order by the time of editing the first post.

Any ideas for that?

Thanks.

**Comment by daohoangson** [comment]
That's not supported for now.

Actually, I think it's not feasible without huge performance hit.

**Comment by kenthd** [comment]
Is there any way to add an event when editing the first post and assign it to a new column in xf_thread?

**Comment by kenthd** [comment]
Because if we can assign timedate as soon as we have the first post edit event  (the example column named "update" in the xf_thread table ), we can add the order type "thread_update_firstpost_reverse"

**Comment by daohoangson** [comment]
That is doable. You will also need to add an index to make sure the query doesn't scan through all the rows of xf_thread table.

**Comment by kenthd** [comment]
Do you intend to update it?

**Comment by daohoangson** [comment]
Oh no, this is out of scope for this add-on :) We only expose XF core data.

**Comment by kenthd** [comment]
Can you give me some directions? Thanks.

**Comment by daohoangson** [comment]
I think you can extend `XenForo_DataWriter_DiscussionMessage_Post::_postSave`, it will run every time a post is inserted/updated. You should be able to update your `xf_thread.first_post_last_edit_date` column from there.

Finally, extend `bdApi_ControllerApi_Thread` and implement a new action for your new order.

**Comment by kenthd** [comment]
Thank. I will try it ;)

**Comment by daohoangson** [comment]
Good luck with your project, let me know if you need further assistance.
