### ISSUE TITLE
Class 'Xfrocks\Api\DevHelper\Admin\Controller\Entity' not found

### ISSUE THREAD

**Issue by mjaschen** [xfrocks/bdApi#108]
Hi there,

I'm trying to get the xenforo2 branch running with XF 2.0.12.

After cloning the repository, checking out the `xenforo2` branch, running `composer install` and importing the data via `php cmd.php xf-dev:import -a Xfrocks/Api` I can successfully call the `/api/` endpoint.

However, opening the API settings in the AdminCP (`/admin.php?api-clients/`) renders an error:

```
Fatal error: Class 'Xfrocks\Api\DevHelper\Admin\Controller\Entity' not found in /home/[...]/forum-next/src/addons/Xfrocks/Api/Admin/Controller/Entity.php on line 7
```

The file containing the aforementioned class is excluded in `.gitignore`:

```
/DevHelper/Admin/Controller/Entity.php
/DevHelper/autogen.json
/_build/
/_data/
/_output/templates/admin/bdapi_entity_delete.html
/_output/templates/admin/bdapi_entity_edit.html
/_output/templates/admin/bdapi_entity_list.html
/_releases/
/vendor/
```

Is there any chance to get that file?

Best regards

Marcus

**Comment by daohoangson** [comment]
You will need to setup https://github.com/xfrocks/DevHelper/tree/xf2 if you wish to clone this repo and do api development. Otherwise you can install with the zip package from https://xfrocks.com/resources/bd-api-for-xenforo-2-0.36/.

**Comment by mjaschen** [comment]
Hi,

thanks, that's exactly the information I needed :-)

Have a great day and thanks for your work!

Marcus
