### ISSUE TITLE
Support for Xenforo 2.1?

### ISSUE THREAD

**Issue by Lachee** [xfrocks/bdApi#109]
I was wondering if this library has been updated to support Xenforo 2.1 and their built in REST api yet. Their new REST api is all well and good, however it isn't a oAuth flow. This breaks all the previous apps we have integrated with our forum.

**Comment by kenthd** [comment]
When I upgraded xf 2.1.0, api was conflicted. Is there any solution?

**Comment by mauzao9** [comment]
Yes @daohoangson you're our only hope, xF 2.1 has no other option that has oauth, would this happen?

**Comment by daohoangson** [comment]
We are working on XF2.1 support. The current plan is: bdapi will bypass built-in api because the exposed entry points are incompatible. That means: if you choose to use bdapi, the built-in api will be completely disabled / ignored. There are complications with the /api/ path because both systems use it, we are looking for ways to work around that. One possible solution if you want to use both (bdapi + built-in api) is to rename bdapi directory from `api` to something else (e.g. `oauthapi`).

**Comment by Lachee** [comment]
A simple rename would suffice for the most part as the API base can be changed relatively simply on our apps.

**Comment by mjaschen** [comment]
I don't know if disabling XenForo's built-in API is the best solution for this problem, as one may use or plan to use XF's API for some tasks and bdAPI for oAuth related things at the same time.

I'm with @Lachee here, choosing another path to the bdAPI would be a good solution (at least for me).

Thanks!

**Comment by daohoangson** [comment]
[Beta 2](https://xfrocks.com/resources/bd-api-for-xenforo-2-0.36/) has been released which supports both XenForo 2.0 and 2.1.

If you want to running the add-on api on a different directory (e.g. `bdapi`), change the api directory when you upload into something else and add this into `config.php`:

```php
$config['api'] = [
    'apiDirName' => 'bdapi',
];
```

**Comment by mjaschen** [comment]
@daohoangson Thanks, that are great news!

**Comment by zernyu** [comment]
@daohoangson Very exciting update, thank you! The `config.php` `apiDirName` option doesn't seem to have any effect for me though...

I have tried:
1) Before installation, rename `api` to `bdapi`, edit `config.php`, install addon. The `api` directory is not found during the installation process.
2) After installation, rename `api` to `bdapi`, edit `config.php`. Navigating to `domain/bdapi` gives a 404.

Am I missing something obvious here?

Thank you for your work here!

**Comment by mjaschen** [comment]
> 2\. After installation, rename `api` to `bdapi`, edit `config.php`. Navigating to `domain/bdapi` gives a 404.

Did you also try a request against `domain/bdapi/` (trailing slash)?

I installed it as you described in (2) and it works for me.

**Comment by zernyu** [comment]
Nope, trailing slash didn't help...

src/XF.php
```php
...
public static $version = '2.1.0';
public static $versionId = 2010070; // abbccde = a.b.c d (alpha: 1, beta: 3, RC: 5, stable: 7, PL: 9) e
...
```

src/config.php
```php
...
$config['api'] = [
        'apiDirName' => 'bdapi',
];
```

`api` directory in XenForo root directory has been renamed to `bdapi`. Navigating to `domain/bdapi` and `domain/bdapi/` both give the 404 page:
```
Oops! We ran into some problems.
The requested page could not be found.
```

Trying to use `domain/api` gives an `endpoint not found` error until I disable the bdApi plugin.

Not sure what other information I can provide to be more helpful in debugging... I'm testing this in a vanilla install of XF 2.1

**Comment by mjaschen** [comment]
> Oops! We ran into some problems.
> The requested page could not be found.

Did you check the XF error log and the web server's error log for any hints?

**Comment by zernyu** [comment]
Nothing in the error logs (these would be all the log tables in MySQL, correct?). Just a 404 in nginx...

**Comment by mjaschen** [comment]
@zernyu One last idea. Does adding

```
location /bdapi/ {
    try_files $uri $uri/ /bdapi/index.php$is_args$args;
}
```

to your nginx config change anything?

**Comment by zernyu** [comment]
@mjaschen Thank you, very clever!! I'm able to use bdApi now 🥳 ... but I'm still left with the issue with the clobbered XF2.1 api routes...

With bdApi disabled:
`curl -H "Content-Type: application/x-www-form-urlencoded" -H "XF-Api-Key: the-key" "http://the.domain/xenforo/api/threads"`
Returns the proper Threads response

With bdApi enabled:
`curl -H "Content-Type: application/x-www-form-urlencoded" -H "XF-Api-Key: the-key" "http://the.domain/xenforo/api/threads"`
Returns:
```json
{
    "errors": [
        {
            "code": "endpoint_not_found",
            "message": "Requested endpoint cannot be found.",
            "params": {
                "reason": "invalid_route"
            }
        }
    ]
}
```

You are not experiencing this?

**Comment by mjaschen** [comment]
@zernyu I checked it and it's the same issue here.

@daohoangson bdAPI works fine after changing the bdAPI directory in `config.php` and renaming the directory accordingly. Unfortunately XF's internal REST API is now defunct:

Trying to load an API resource

```
curl -H 'XF-Api-Key: <KEY>' https://xenforo.example.org/api/threads/1234
```

gives an error

```json
{
  "errors": [
    {
      "code": "endpoint_not_found",
      "message": "Requested endpoint cannot be found.",
      "params": {
        "reason": "invalid_route",
        "debug_reason": "invalid_route",
        "debug_controller": null,
        "debug_action": null
      }
    }
  ]
}
```

**Comment by daohoangson** [comment]
We are aware of both issues and fixes are being worked on. New version is coming soon.

**Comment by daohoangson** [comment]
[Beta 3](https://xfrocks.com/resources/bd-api-for-xenforo-2-0.36/) has been released with the fixes for hashes and built-in api conflict.

**Comment by mjaschen** [comment]
@daohoangson Thank you very much!

**Comment by zernyu** [comment]
I was able to successfully use the User Credentials flow which is super exciting. But now that I'm implementing the Authorization Code flow, I've run into an issue:

Going to `/xenforo/bdapi/index.php?oauth/authorize&response_type=code&client_id=<client_id>&redirect_uri=<url>` gives an error of "Invalid client." I've double and triple checked the client id...

Also, why is there no button to create an API client? It took me a while to find that there is a URL for creating a client
<img src="https://user-images.githubusercontent.com/585617/53241110-9eb65d00-36db-11e9-9740-c8477b2fa097.png" width=200>

**Comment by zernyu** [comment]
Ah, looks like `redirect_uri` must match exactly with what's set in the API Client. My apologies.

The create API Client button is no biggie, probably a low priority for you as well. Looks like things are working now. Thank you for your great add-on :)

**Comment by Lachee** [comment]
The create client button is under your user settings. Just make sure you have permission set on the user for it

**Comment by zernyu** [comment]
Ah... did not realize there were permissions regarding that. Thank you!

**Comment by daohoangson** [comment]
> Ah, looks like `redirect_uri` must match exactly with what's set in the API Client. My apologies.

@zernyu you can set a whitelist domain to avoid having to specify one redirect_uri beforehand.

**Comment by daohoangson** [comment]
I'm closing this issue as it has been resolved.

Download the latest beta at https://xfrocks.com/resources/bd-api-for-xenforo-2-0.36/
