### ISSUE TITLE
how do i login with andriod  app? can't find the api

### ISSUE THREAD

**Issue by cyuxlif** [xfrocks/bdApi#11]

**Comment by daohoangson** [comment]
You can try the demo Android project [here](https://github.com/xfrocks/bdApi/tree/master/android_demo).

**Comment by JulianD** [comment]
I have an android app which logs in the user against this API. I'm using Retrofit2. With an Okhttp interceptor I can tell if I'm logged in or not, refresh the token or even ask for a new one (i'm storing the user and password inside my app). This is the tutorial that I followed, obviously you need to adapt the oauth requirements to what this API needs.

**Comment by daohoangson** [comment]
@JulianD I think you missed a link. Would love to get a copy of the Retrofit2 interfaces if possible too. I have always wanted to do a demo with Retrofit2 + OkHttp, maybe a PR? :dancer:

**Comment by JulianD** [comment]
@daohoangson oops.. Here's the link: https://futurestud.io/blog/oauth-2-on-android-with-retrofit

I still need to figure out some bugs with my implementation but I'm sure once I get it right I might contribute to your android app :)

**Comment by cyuxlif** [comment]
thank you guys, I will try.
