### ISSUE TITLE
File integrity check fails if API directory is renamed

### ISSUE THREAD

**Issue by mjaschen** [xfrocks/bdApi#111]
Hi!

I've installed the latest beta and renamed the `api/` directory to `bdapi/` and added the setting in `config.php` accordingly.

XenForo's integrity check now complains an error about missing files:

![](https://dl.dropboxusercontent.com/s%2Fccwporcprzqiwdh%2Fscreenshot_2019-02-14_14-13-05.jpg)

**Comment by daohoangson** [comment]
This one is tricky to solve because the hashes are computed at build time...

**Comment by mjaschen** [comment]
Is it possible to exclude the two files from hash calculation?

**Comment by daohoangson** [comment]
Yes, we will exclude the directory for hashes.

**Comment by daohoangson** [comment]
[Beta 3](https://xfrocks.com/resources/bd-api-for-xenforo-2-0.36/) includes the fix for this issue. Please take the time to upgrade @mjaschen
