### ISSUE TITLE
Parse error: syntax error, unexpected ')' in \library\bdApi\ControllerApi\Post.php on line 566

### ISSUE THREAD

**Issue by suj87** [xfrocks/bdApi#128]
This file has an error, which is an extra comma at the end of line 565: `$pageNavParams,`

The fix is to remove the comma: `$pageNavParams`

You won't see this error unless you manually look at the response - the request doesn't show up in the api logs.

**Comment by daohoangson** [comment]
Ah, this looks like an overlook on my part. The trailing commas have been allowed since PHP 7.3 but will cause issue if you are running an earlier version. I'll have to recheck the whole repo to find other places that have this kind of bug.

What is your PHP version by the way?

**Comment by suj87** [comment]
> Ah, this looks like an overlook on my part. The trailing commas have been allowed since PHP 7.3 but will cause issue if you are running an earlier version. I'll have to recheck the whole repo to find other places that have this kind of bug.
> 
> What is your PHP version by the way?

Yes I figured this would be a PHP version issue as I was looking at the file and noticed more trailing commas. PHP version on my local dev machine is 5.4.12 (very old WAMP setup that needs updating).

**Comment by daohoangson** [comment]
This has been fixed in #129, I have also added extra measures in place to avoid similar issues in the future. Let me know if it works for you.

**Comment by suj87** [comment]
> This has been fixed in #129, I have also added extra measures in place to avoid similar issues in the future. Let me know if it works for you.

I just downloaded the new version from the XF website, unzipped (overwrote all files) and ran the xml file. Bug looks fixed, many thanks.

**Comment by daohoangson** [comment]
Awesome. I'm closing this now.
