### ISSUE TITLE
(object:XenForo_BbCode_TextWrapper) in logs

### ISSUE THREAD

**Issue by suj87** [xfrocks/bdApi#130]
When using, for example, `PUT ` to update a post, under the response header, any "html" properties e.g. `post_body_html` or `signature_html` are displaying `(object:XenForo_BbCode_TextWrapper)` rather than the actual html. (The actual html in the JSON received on the client end is fine though).

PHP ver: 5.4.12
BDApi: 1.6.3 (downloaded from Xenforo BDApi page)

**Comment by daohoangson** [comment]
Yes, this is expected. The log does not keep everything to avoid storing too much information in the database, doing so will negatively impact the api performance.
