### ISSUE TITLE
Authorization: Bearer <access_token>

### ISSUE THREAD

**Issue by DSpeichert** [xfrocks/bdApi#15]
When requesting resources, bdAPI seems to accept `oauth_token` request parameter.
According to specs I read, passing the access token in `Authorization` header is the preferred method. bdApi seems to always return `"error": "invalid_request"` when I attempt that form of authorization. Is it supported?

**Comment by DSpeichert** [comment]
Sorry, the forum was not using the latest version of bdAPI.

**Comment by daohoangson** [comment]
Ah, good to know 👍
