### ISSUE TITLE
[request] Alert Support

### ISSUE THREAD

**Issue by Lachee** [xfrocks/bdApi#17]
Would it be possible to add suport for the POST scope to be able to push alerts to users? Would be very helpful to give users notifications of things that have happened with the application they have signed in with without the need of creating conversations or posts with their user tag in it.

**Comment by daohoangson** [comment]
Nice idea. We will see what is possible.

**Comment by Lachee** [comment]
Did this turn out to be possible? Revisiting the project that used this api and it would still be very nice to be able to send alerts to users.

**Comment by daohoangson** [comment]
Actually there is one undocumented api to send alert to user using some
admin user access token. POST
`/tools/ping?oauth_token=xxx&user_id=123&message=foo+bar`.

Doing this will send an alert to user 123 from your account with content
"foo bar".
