### ISSUE TITLE
Can't get the token, malformated uri.

### ISSUE THREAD

**Issue by BerkanYildiz** [xfrocks/bdApi#20]
Hi,

When i click on the 'Authorize Access' button, at example.com/account/authorize, it redirect me to the callback url, but the parameters are after a '#', not a '?', so i can't get them using PHP.

eg : https://www.gobelinland.fr/callback.php#access_token=blabla&user_id=1

**Comment by daohoangson** [comment]
You were using the Implicit grant type, it's designed for client side application (JavaScript app etc.).
If you wish to handle the token server side with PHP, use the Authorization code grant type.

**Comment by BerkanYildiz** [comment]
I don't understand how works the Server Side one, i never worked with classes :(

**Comment by daohoangson** [comment]
You can read the example code here https://github.com/xfrocks/bdApi/blob/master/php_demo/index.php
