### ISSUE TITLE
Can't retrieve access token, throws 403

### ISSUE THREAD

**Issue by rgbvader** [xfrocks/bdApi#22]
This is probably just an issue with my code, but whenever I attempt to retrieve an access code I get an http 403 response.
After getting the code from `oauth/authorize`, I attempt to get an access code using RFC 6749's specifications.
The request data is sent below, other than some private data blurred out. (using GuzzleHttp)
![firefox_2017-04-29_17-59-13](https://cloud.githubusercontent.com/assets/25411032/25559325/a2acf6d0-2d05-11e7-9d31-f81d94fb4d35.png)
response:
```
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr> (truncated...)
```

Again sorry if this isn't the proper place to put this, but I cannot post to your forums since I'm linked to someone's XF purchase, not having my own.

**Comment by daohoangson** [comment]
The request looks good. Are you sure the `redirect_uri` is correct? It should match its value during user authorization.

**Comment by rgbvader** [comment]
Yes, sir. It's the same value

**Comment by daohoangson** [comment]
Do you have access to the server? Can you check database table `xf_bdapi_auth_code` and see if your code is there? Also, please make sure other fields have expected values while you are there too.

**Comment by rgbvader** [comment]
I'll check and report back

**Comment by rgbvader** [comment]
I can confirm that it does indeed exist, and by fields do you mean `client_id` and such? If so, those are also valid.

**Comment by daohoangson** [comment]
I think the 403 came from your web server instead of the php application. Which web server are you running? Does it have any firewall / security rules etc.?

**Comment by rgbvader** [comment]
Sorry for the delayed response, the request seems to go through fine when using Postman, so it must be something I am doing. Thanks for throwing some ideas around.
