### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by Mo7mud** [xfrocks/bdApi#23]
Hi,
Thank you for this api,
Can you please give us detailed installation guide?
I can't get it to work as I don't what's the steps to prepare it.
What;s the redirect uri?
what's the fields in AdminCP and android app suppose to mean? and how to get this keys?

**Comment by daohoangson** [comment]
You can get the add-on bundle here. The website has installation instruction.

https://xenforo.com/community/resources/bd-api.1732/

**Comment by Mo7mud** [comment]
Yes thank you I saw it.
Sorry for late reply
