### ISSUE TITLE
Access to data denied even with valid oauth_token

### ISSUE THREAD

**Issue by FlorianSW** [xfrocks/bdApi#25]
Hi,

I've developed an extension for MediaWiki, which integrates a login with a user from XenForo using this bdApi. However, since some time, the login is not possible anymore for at least two users of this extension. The reason is, that, even with a valid oauth_token parameter, the request of the users/me endpoint fails with an error: "You've to be a member of this site". However, if I make the request in my browser (where I can reproduce this behaviour) a second time, I get all data.

Now, I'm not sure, if this is a problem with the settings of the forum, a bug in my extension or a bug in this addon. Could you help me finding this out? :)

The returned error message is:
`{"errors":["Um diese Aktion durchf\u00fchren zu k\u00f6nnen, musst du ein angemeldetes und registriertes Mitglied dieser Seite sein."]}`

**Comment by daohoangson** [comment]
That phrase (You've to be a member of this site) seems to be from an add-on so it's likely that some add-on prevents the api from returning data for `/users/me`. Can you check installed add-ons and find the one that is causing issue?

**Comment by FlorianSW** [comment]
I requested a list of addons from one of the users who has the problem. However, I'm not sure, if really another addon causes this error message, as it is the same as when I pass an invalid oauth_token (however, like I said, the oauth_token is the one I got from the OAuth process and it is working if I make the request the second time).

**Comment by FlorianSW** [comment]
Hi, here's the list of the installed addons. I can't imagine, that one of them could result in this behaviour:
Ads Manager 1.25.1
All Rich Usernames 1.1.0
Convert Image 5.0
Convert Image All 5.7
Custom Tabs 1.2.0
Defer JS 2.2.4
Digital Point Syntax Highlighter 1.3.0
Mark Post as Best Answer 1.6.1
Post Ratings 1.7.5
s9e Media Pack 20161112
sonnb - Prevent double post 1.0.1
TAC De-Dos - Reduce the effect DOS attacks usually caused by spam bots 1.3.05
XenCentral Framework 1.1.6
XenCentral Invitation & Paid Registration System 1.1.4.2
XenForo Resource Manager 1.2.3
XFA - Bump Thread 1.2.0
[8wayRun.Com] XenPorta 2 (Portal) PRO 1.1.9
[8WR] Discord Integration 1.0.8
[AD] UI.X 1.0.12a
[bd] API 1.5.1
[bd] Medal 1.5.0b
[HA] Loading Effects 1.0.1
[ThemesCorp] Projects Manager 2.0.1
[VietXF] Custom Node Icon 0.9

**Comment by ghost** [comment]
Can you do a phrase search for the error message and give me the phrase
title?

**Comment by FlorianSW** [comment]
Hi,

Here the result of the grep:
C:\xampp\htdocs\library\bdApi\ControllerApi\Error.php (1 hit)

                Line 61:                return $this->responseError(new XenForo_Phrase('must_be_registered'), 403);

C:\xampp\htdocs\library\XenForo\ControllerPublic\Error.php (1 hit)

                Line 82:                //'text' => new XenForo_Phrase('must_be_registered')

Hope that helps.

**Comment by luutruong** [comment]
Does you have latest code from there not in XenForo.com? Cause that xfrocks did not update on that site..

**Comment by FlorianSW** [comment]
What do you mean exactly, should the users use the github master of this addon instead of the xenforo.com version?

**Comment by luutruong** [comment]
@FlorianSW  Yes. Exactly.

**Comment by FlorianSW** [comment]
Ok, the user installed the latest version of the addon but get's the same error message.

**Comment by daohoangson** [comment]
This is strange, do you happen to have http auth headers for request made by your extension? Since the token works with browser, it appears to be correct.

**Comment by FlorianSW** [comment]
Ok, here're the headers and the responses. To be sure, we haven't misunderstand each other: The token works in the browser only, if I reload the error page. That means, after I've got the oauth_token I paste it into an incognito tab of Chrome, load the page and get the same error message as my extension. If I then reload the page, I get the expected user information response. So I wouldn't really say, that it is fully working, the reload shouldn't be necessary.

The first request (to gte the oauth_token and the access to the user data from the user):
```
Method: POST https://www.example.com/api/index.php?oauth/token
Request data: array(5) {
  ["grant_type"]=>
  string(18) "authorization_code"
  ["client_id"]=>
  string(10) "xxxxx"
  ["client_secret"]=>
  string(15) "xxxxx"
  ["code"]=>
  string(40) "xxxxx"
  ["redirect_uri"]=>
  string(188) "http://localhost/w/index.php?title=Special:UserLogin/return&wpLoginToken=53c28e7f3c435de686dbcd90c1d815375924a5f0%2B%5C&returnto=Hauptseite&returntoquery=mobileaction%3Dtoggle_view_desktop"
}
```

Response header:
```
array(11) {
  ["Server"]=>
  string(5) "nginx"
  ["Date"]=>
  string(29) "Tue, 23 May 2017 21:13:29 GMT"
  ["Content-Type"]=>
  string(31) "application/json; charset=UTF-8"
  ["Content-Length"]=>
  string(3) "227"
  ["Connection"]=>
  string(5) "close"
  ["Expires"]=>
  string(29) "Thu, 19 Nov 1981 08:52:00 GMT"
  ["Cache-control"]=>
  string(18) "private, max-age=0"
  ["Last-Modified"]=>
  string(29) "Tue, 23 May 2017 21:13:29 GMT"
  ["Cache-Control"]=>
  string(8) "no-store"
  ["Pragma"]=>
  string(8) "no-cache"
  ["Strict-Transport-Security"]=>
  string(16) "max-age=31536000"
}
```

Response Status: 200 HTTP/1.1 200 OK
Response:
```
{"access_token":"yyy","expires_in":"3600","token_type":"Bearer","scope":"read","refresh_token":"ccc","user_id":102719,"refresh_token_expires_in":1209600}
```

Second request (to get the user information):
```
Method: GET https://www.example.com/api/index.php?users/me&oauth_token=yyy
```

Response header:
```
array(10) {
  ["Server"]=>
  string(5) "nginx"
  ["Date"]=>
  string(29) "Tue, 23 May 2017 21:13:29 GMT"
  ["Content-Type"]=>
  string(31) "application/json; charset=UTF-8"
  ["Content-Length"]=>
  string(3) "135"
  ["Connection"]=>
  string(5) "close"
  ["Expires"]=>
  string(29) "Thu, 19 Nov 1981 08:52:00 GMT"
  ["Cache-control"]=>
  string(18) "private, max-age=0"
  ["Set-Cookie"]=>
  string(96) "xf_logged_in=1; expires=Thu, 22-Jun-2017 21:13:29 GMT; Max-Age=2592000; path=/; secure; HttpOnly"
  ["Last-Modified"]=>
  string(29) "Tue, 23 May 2017 21:13:29 GMT"
  ["Strict-Transport-Security"]=>
  string(16) "max-age=31536000"
}
```

Response Status: 403 HTTP/1.1 403 Forbidden
Response:
```
{"errors":["Um diese Aktion durchf\u00fchren zu k\u00f6nnen, musst du ein angemeldetes und registriertes Mitglied dieser Seite sein."]}
```

**Comment by daohoangson** [comment]
> That means, after I've got the oauth_token I paste it into an incognito tab of Chrome, load the page and get the same error message as my extension. If I then reload the page, I get the expected user information response.

This indicates a different issue I think. Can you try again but wait for a while (e.g. 5 minute) before using the new token? I can't think of any reason preventing it from working the first time but then let it work afterwards.

**Comment by FlorianSW** [comment]
Hmm, waiting sounds like a strange idea, however, I did it. I'd the same result, here are the request/response information:

```
Request URL:https://www.example.com/api/index.php?users/me&oauth_token=yyy
Request Method:GET
Status Code:403 Forbidden
Remote Address:212.72.171.241:443
Referrer Policy:no-referrer-when-downgrade
```

Response Headers
```
Cache-control:private, max-age=0
Connection:close
Content-Length:135
Content-Type:application/json; charset=UTF-8
Date:Wed, 24 May 2017 15:32:56 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Last-Modified:Wed, 24 May 2017 15:28:59 GMT
Server:nginx
Set-Cookie:xf_logged_in=1; expires=Fri, 23-Jun-2017 15:28:59 GMT; Max-Age=2592000; path=/; secure; HttpOnly
Strict-Transport-Security:max-age=31536000
```

Request Headers
```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Host:www.android-hilfe.de
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
```

Query String Parameters
```
users/me:
oauth_token:yyy
```

```
Request URL:https://www.example.com/api/index.php?users/me&oauth_token=yyy
Request Method:GET
Status Code:200 OK
Remote Address:212.72.171.241:443
Referrer Policy:no-referrer-when-downgrade
```

Response Headers
```
Cache-control:private, max-age=0
Connection:close
Content-Encoding:gzip
Content-Type:application/json; charset=UTF-8
Date:Wed, 24 May 2017 15:33:24 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Last-Modified:Wed, 24 May 2017 15:33:24 GMT
Server:nginx
Strict-Transport-Security:max-age=31536000
Transfer-Encoding:chunked
Vary:Accept-Encoding
X-Cache:BYPASS

```
Request Headers
```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Cache-Control:max-age=0
Connection:keep-alive
Cookie:xf_logged_in=1
Host:www.android-hilfe.de
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
```

Query String Parameters
```
users/me:
oauth_token:yyy
```

**Comment by FlorianSW** [comment]
Ok, if I send the following additional Request header to the first request where I use the oauth_token:
`Cookie: xf_logged_in=1`
I get a valid reponse with the data I requested. However, this shouldn't be necessary, and, of course, this does not provide any additional security :(

**Comment by daohoangson** [comment]
So I have looked through XenForo source code and there is no cookie named `logged_in` so that's probably some sticky cookie implemented by the load balancer / web server to route request to guest / member servers etc. Which explains why visiting via browser worked for the 2nd time.

Can you ask your users and see if they have something like that in place?

**Comment by FlorianSW** [comment]
Hi @daohoangson! Thanks for your help! :) I looked around and searched for an addon which could set this cookie, and there seems to be an addon:
https://xenforo.com/community/resources/logged-in-cookie.4961/

As far as I know about the XenForo forum we're talking about, it would make totally sense for them to use this addon (and a Varnish frontend cache or something like this), however, I asked them to clarify this.

I'm not totally sure, how this can be solved. If it is really related to the cache, then the issue is (most-likely) not related to this addon, but to the cache configuration of the forum.

I'll report back!

**Comment by daohoangson** [comment]
Hi @FlorianSW, have you figured this out yet?

**Comment by FlorianSW** [comment]
Hi @daohoangson, until now, I've unfortunately got no answer from the forum owner and the technical responsible :( I'll answer here as soon as I got an answer from them :) Thanks for your patience!

**Comment by FlorianSW** [comment]
Ok, it seems the owner of the XenForo forum is not really interested in looking into this and fixing it. As this seems to be an error in the configuration of that particular board and not with this addon at all, I'll close this issue. There's no need, why it needs to stay open here.

@daohoangson Big Thanks nevertheless for your support and helping tracking this problem down, it was quite funny :)

**Comment by PatPeter** [comment]
It looks like this issue was trying to [implement a [bd] API client for the XenForoAuth MediaWiki extension](https://www.mediawiki.org/wiki/Extension:XenForoAuth). I'm dealing with [the same issue](https://github.com/xfrocks/bdApi/issues/38) and it's sad to see that this was unresolved.

**Comment by daohoangson** [comment]
@PatPeter yours is different I think. Also, this appeared to be a configuration issue not a bug, we tried our best to offer support.
