### ISSUE TITLE
NodeJS passport 

### ISSUE THREAD

**Issue by ethan-gallant** [xfrocks/bdApi#27]
I am fairly new to using the API but after three days of straining my eyes I have decided to ask. I am unsure of how to use this with passport and I have tried practically everything I know.

If someone could give me an example or a repo where someone else has done it, it would make my day.

**Comment by daohoangson** [comment]
The library doesn't seem to handle `index.php?oauth/authorize` and `index.php?oauth/token` correctly so you will need to use the rewritten versions. The below code worked for me.

```js
  passport.use(new OAuth2Strategy({
      authorizationURL: 'https://domain.com/xenforo/api/oauth/authorize',
      tokenURL: 'https://domain.com/xenforo/api/oauth/token',
      clientID: 'xxx',
      clientSecret: 'yyy',
      callbackURL: "http://localhost:3000/auth/example/callback"
    },
    function(accessToken, refreshToken, profile, cb) {
      console.log(accessToken, refreshToken);
      cb(null, profile);
    }
  ));

  app.get('/auth/xenforo', passport.authenticate('oauth2'));

  app.get('/auth/xenforo/callback',
    passport.authenticate('oauth2', { failureRedirect: '/oops' }),
    function(req, res) { res.redirect('/ok'); }
  );

```

**Comment by ethan-gallant** [comment]
It gives me a"

```
Error
The requested page could not be found.
```

 The url I get redirected to is 

`https://website.com/xenforo/api/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fxenforo%2Fcallback&client_id=e8osocya9d`

if that helps.

**Comment by daohoangson** [comment]
Is https://website.com/xenforo/api accessible? How about https://website.com/xenforo/api/search? You need to replace your site address properly. With xfrocks.com, we have XenForo at root so the `authorizationURL` is https://xfrocks.com/api/oauth/authorize for example.

**Comment by ethan-gallant** [comment]
https://nauticmc.com/api/ it works for me but i have to add an /index.php?oauth/authorize . Im not sure if that has anything to do with it. I have tried to add that in the config but then it just outputs what you would get if you just typed index.php without anything else. 

Here is the url:
`https://nauticmc.com/api/index.php?oauth%2Fauthorize=&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fxenforo%2Fcallback&client_id=e8osocya9d`

**Comment by daohoangson** [comment]
https://nauticmc.com/api/search doesn't work so it looks like you need to configure your web server a bit further. Do you use Apache or nginx? For Apache, copying .htaccess from the root directory into `api` directory should be enough.

**Comment by ethan-gallant** [comment]
Great it works! Now how would i go about accessing the users data?

**Comment by daohoangson** [comment]
With the access token, you should be able to access XenForo data according to this document https://github.com/xfrocks/bdApi/blob/master/docs/api.markdown

**Comment by ethan-gallant** [comment]
So I would need to make a request to /users/me inside of     ```
function(accessToken, refreshToken, profile, cb) {
        console.log(accessToken, refreshToken);

        cb(null, profile);
    }
```
That gets that users profile then callback with the real profile?

For example:
function(accessToken, refreshToken, profile, cb) {
        console.log(accessToken, refreshToken);
        request('/users/me',(body)=>{
cb(null, body);
}
        
    }
```

**Comment by daohoangson** [comment]
Yes, that should do it. Or if you only need the XenForo user_id, it is included in the token response. However the Passportjs library seems to discard that info during its processing.

**Comment by ethan-gallant** [comment]
So how exactly do i authenticate with the clients credentials on the server side to get the user info? Do i pass the accesstoken as a parameter or....

**Comment by ethan-gallant** [comment]
Never mind I figured it out. Thank you so much for your help with this @daohoangson .
