### ISSUE TITLE
javax.net.ssl.SSLProtocolException

### ISSUE THREAD

**Issue by Mo7mud** [xfrocks/bdApi#30]
Hi,
I'm facing this error since I installed a SSL certificate on the domain:

```
Error=com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x5f53f1f0: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x59c648f0:0x00000000)

```
This is happening only on android versions lower than M

I tried those solutions but with no luck:
https://stackoverflow.com/questions/29916962/javax-net-ssl-sslhandshakeexception-javax-net-ssl-sslprotocolexception-ssl-han
https://stackoverflow.com/questions/32184787/com-android-volley-noconnectionerror-javax-net-ssl-sslhandshakeexception-javax

https://stackoverflow.com/questions/30925213/ssl-exception-when-using-volley

Whin using http not https there is no issue
The issue occurs only when using https on Android version lower than M
Any help will be appreciated 
Thank you

**Comment by daohoangson** [comment]
This is an issue with your server TLS configuration and your app rather than an issue with the API itself. I guess your server uses a modern cipher suite and older Android version just doesn't support it. This is not something we can help you here, sorry.
