### ISSUE TITLE
Are there installation instructions?

### ISSUE THREAD

**Issue by drlukeangel** [xfrocks/bdApi#34]
Hello,
   Are there installation instructions?
   Not seeing them in the readme. 
Thanks, 
   Luke

**Comment by daohoangson** [comment]
HI @drlukeangel,

You can read about that here https://xenforo.com/community/resources/bd-api.1732/. Sorry for the confusion.

**Comment by drlukeangel** [comment]
Hello Daohoangson,
   Thanks for the fast reply. 
   I coudn't find the api page on xenforo  or xfrocks xenforo instance kind of strange. 
   There system isn't really the best for discovery. 
   Might be a idea to keep this in the the readme.md in the git repo. 
   Thank you for your effort in getting this resource together. 
   This api module is what made me choose xeno of phpBB. 
   Do you do consulting work? 
   The contact page link on the xfrocks page does not link to anything. 
Thanks
Luke

**Comment by daohoangson** [comment]
Hi,

Yes I do. Please contact me via email pony at xfrocks dot com. Thank you.

**Comment by drlukeangel** [comment]
So a bit of newbie on this software so bare with me. 
I am reading the directions and it says 
1. Upload files and directories inside `upload` to XenForo's root directory. Select "Merge" for everything if you are asked
what do you mean inside the 'upload'?  i read this as there is a folder called upload when i open this repo is the below image. Thanks
![image](https://user-images.githubusercontent.com/22433329/33052666-ca3624f4-ce24-11e7-9187-be8a86863b4a.png)

**Comment by drlukeangel** [comment]
ok i got it installed but what is the root of the API? Assuming xen is installed at root.. is it www.mysite.com/api/...

**Comment by daohoangson** [comment]
Hi @drlukeangel,

Have you commented something and removed it? Are you still having problem with installing this add-on?

**Comment by drlukeangel** [comment]
ill wrap it up in a comment there are some things that could be worded better. I have the installation done correctly but now i am struggling with getting the api to function properly. It most likely has to do with how the oauth is set up. Ill look at it again tomorrow.
   Can you clarify something.that this works correctly on standard http calls ? 
So assuming the forum is the root of the website http://www.mysite.com"
   1.  I take the key and secret and authenticate to get a token?
    2. Once i have the token how am i passing it around? header, Paramater? what is the name of the property (bearer_token , some-security-token, ... )
    3. From there i could  do a  curl  GET http://www.mysite.com/api/categories/
that should return a [category] or a array of categories? Want to clarify that the api's root is http://mysite.com/api/
    If you could answer me those questions i could  get up and running alot faster.

**Comment by daohoangson** [comment]
1. Correct
2. You can use URL param `oauth_token` or HTTP header `Bearer`
3. You will get a JSON reponse with a list of categories. 

For more info, check the document here https://github.com/xfrocks/bdApi/blob/master/docs/api.markdown

**Comment by drlukeangel** [comment]
Issue can not create a token from the admin section 
------------------ 
hello so add new token doesn't appear to be working on the admin site 
I go here 
http://51.143.97.191/admin.php?api-tokens/add
input the data below 
dont worry about this server ill trash it tommorrow 
![image](https://user-images.githubusercontent.com/22433329/33106480-15a489e0-cee7-11e7-8d36-28350fc1303a.png)
nothing happens
go into access tokens and its empty. i would think this would generate a api token that i could use to start making calls. 
![image](https://user-images.githubusercontent.com/22433329/33106522-4fb44cec-cee7-11e7-972d-71112a544290.png)
here is the client info

![image](https://user-images.githubusercontent.com/22433329/33106584-b2242564-cee7-11e7-8d3c-63c16b4a137c.png)

i made a admin account on the server for you if you want to check it out username is github user and password is pony email address.

**Comment by daohoangson** [comment]
I tried logging in but that account doesn't have admin privileges so I couldn't check anything. Your assumption is correct though, it should create a new token after you submit the form. Do you have any server error log? Also, are you using the version on xenforo.com or you checkout the code from this repo?

**Comment by drlukeangel** [comment]
Issue can set a public key
----------------------------------
I generated a public in 5 different formats on mac and pc and none of them would save. 
![image](https://user-images.githubusercontent.com/22433329/33106803-f060361e-cee8-11e7-93ca-7bdfbd77b4af.png)

attached keys
[xenoKeys.zip](https://github.com/xfrocks/bdApi/files/1493664/xenoKeys.zip)

**Comment by daohoangson** [comment]
If you plan to use public key, you can use the front-end interface. It will generate the key pair for you. Go to http://domain.com/xenforo/account/api, click Edit for your Client and click the link below Public Key.

Btw, why did you close this issue?

**Comment by drlukeangel** [comment]
I tried that way i am still getting a error. 
![failedprivate](https://user-images.githubusercontent.com/22433329/33107943-7c6976fc-ceee-11e7-9044-aa832832b712.gif)

**Comment by drlukeangel** [comment]
here is a better video 
https://graph4-my.sharepoint.com/personal/luke_lukeangel_co/Documents/_sharedPublic/apiFailKeyXen.mp4

Not sure whats going wrong here using everything I beleive in the correct way. I am showing you think on a live LAMP stack although i had the same error when running it on my local box.

**Comment by drlukeangel** [comment]
sorry missed two questions. 
**code** location : 
    I am using the code from github.
**User:**
     just use the admin account i made the password 1234 
**API location question**
The site is installed on the root host. I want to clarify if xenoforo is installed on the root of the site that the call should http://51.143.97.191/api/ and not http://51.143.97.191/xenforo/api/ which is listed quite often in the documentation?
**Demo**
I have added your demo code to a folder called demo off the root you can find it here: http://51.143.97.191/demo/
thank you for your assistance.

**Comment by drlukeangel** [comment]
your comment got me about which code version i was using.. since i just bought xeno my account was not licensed on the community forum and i didn't even know you could download it from there. SOOOOOooo after i linked those accounts and then waited 30 minutes.. my community account activated the download link. I downloaded it from xeno and low and behold there is the upload folder you were referencing in your documentation that is not on github(i figured out which one it was anyways), and i uploaded it. By santa's belly all is good everything started to work.  So needless to say the github repo is off somewhere.  I would reference it so someone doesn't lose the hours i lost.   Ill try and submit some pull requests with some updated documentation over the next few weeks. I have alot of working to do on this API in my future.

**Comment by daohoangson** [comment]
Ah, the repo is for development and you are supposed to build the add-on
from the repo. It's not recommend for non-developer.

**Comment by drlukeangel** [comment]
Well the good news its solved.  Also that it exists at all!  Unfortunately you above comment is not documented anywhere. Where are the instructions for compilation of the project? i read all the readme.mds. The way Github works and Git in general is the Master/trunk is your source of truth for whats ready/in production . Development branches are under different branches/tags.   As i go through this API are you interested in having me update the documentation or are you good with the way it is?

**Comment by daohoangson** [comment]
Yeah, you will need to setup the dev env with https://github.com/xfrocks/DevHelper before you can checkout this repo and start working on it. Probably I will leave it as is for now and focus on documenting later when XenForo 2 hits.

**Comment by drlukeangel** [comment]
Hi Đào Hoàng Sơn,
   I sent a email to pony at xfrocks dot com. about a contract for API job. Let me know if you got it.  you can email me at luke at btree dot co
