### ISSUE TITLE
post_body_plain_text contains bbcode

### ISSUE THREAD

**Issue by WuerfelDev** [xfrocks/bdApi#35]
The entry `"post_body_plain_text"` sometimes contains bbcode. As i noticed this applies at least to the `[SIZE]` tag. The `[FONT]` tag for example is working fine.

```
"post_body":"[SIZE=6]mytext[\/SIZE]",
"post_body_html":"<span style=\"font-size: 22px\">mytext<\/span>",
"post_body_plain_text":"[SIZE=6]mytext[\/SIZE]",
```

https://github.com/xfrocks/bdApi/blob/master/docs/api.markdown#get-postspostid

**Comment by WuerfelDev** [comment]
Couldn't this be fixed by just running `strip_tags()` on `"post_body_html"` ?

**Comment by daohoangson** [comment]
It seems to work for me...

```json
"post_body": "[SIZE=6]Size 6.[/SIZE]",
"post_body_html": "<span style=\"font-size: 22px\">Size 6.</span>",
"post_body_plain_text": "Size 6.",
```

The plain text was built by stripping bb code which will generate different output in comparison to stripping tags from html. Can you try again on another XenForo installation? Your issue may be related to some conflict with another add-on.

**Comment by WuerfelDev** [comment]
I noticed that, but it is not my forum installation. So I cant say anything... I'll pass it to the owner
