### ISSUE TITLE
Installation Instructions & Other questions

### ISSUE THREAD

**Issue by SomeRandomDude32** [xfrocks/bdApi#46]
I was searching if there's a way to get information in **json** about a specific user on my forum using their username and password, such as rank or secondary rank, but failed to find any working examples.

Also, is there a proper tutorial or something to get started? I'm having a hard time finding something that clearly explains how to use the api itself.

**Comment by daohoangson** [comment]
We have a few demos which you can take a look and see how it works.

I also have a simple script that verifies username/password here https://gist.github.com/daohoangson/b37d069bc0902b29b8295e555dac9351/ (see the script.php file).

**Comment by SomeRandomDude32** [comment]
Thank you for your reply, I am using xenforo 2 port of BD API, do you think that will affect anything?

Also, is there a way to view user information through a basic url, and could you give an example of that, since it's quite hard go understand what is going on in what you linked.

**Comment by daohoangson** [comment]
The XF2 branch is backward compatible so the demo above should work.

Basic information for a user? You can check out the doc, it lists everything https://github.com/xfrocks/bdApi/blob/master/docs/api.markdown#get-usersuserid

**Comment by SomeRandomDude32** [comment]
Thank you very much again, apologies for my noobiness!

 I've been trying to construct a url which is similar to the ones featured in XenApi, but they are all responding with an invalid link error.

 Even the suggested ones at /API/ respond with the same error. Do you think this could be down to a shotty installation? 

I've been doing it like site.com/api/index.php?users/userid. Is there a proper way to install, as ice just added the add-ons and placed the api directory. Again, I am probably being stupid but could you give a example link for getting a specific users secondary rank from say your xfrocks website.

**Comment by daohoangson** [comment]
As a demo URL, you can check this link https://tinhte.vn/appforo/index.php?users/1/ (this site renamed the `api` directory into `appforo`). The xfrocks.com API is restricted so I cannot give you a working URL (all API endpoints requires a valid token).

**Comment by SomeRandomDude32** [comment]
That link returns valid, but doesn't seem to contain private data (which is good) but what I need. How would the username and password of the user be used in a url similar to this to access private data such as rank? Such as /secondary_user_id

And how would a user id be captured from a username?

Thanks :)

**Comment by daohoangson** [comment]
In the demo script, it will authenticate with an username/password to get a token. Using the token you can request domain.com/api/index.php?users/me&oauth_token=xxx and get all user data including private data like user groups. The demo script actually does a check for user group so you should definitely take a look there.

**Comment by SomeRandomDude32** [comment]
Gotcha.

For the token is there like an example you can provide?
I don't quite understand the source that well :)

**Comment by SomeRandomDude32** [comment]
Hey, thank you for putting up with me. After looking at the script you sent, i've tried to create a URL which (i think) should work to return the TOKEN, but doesn't. 

Using my verison of BD, I can't seem to find anywhere to set the client_secret. 

I was wondering if my interpretation is correct, and if not what i should change it to. Also would the client_id just be the players ID. Many thanks

site.com/api/index.php?oauth/token&grant_type=password&username=USERNAME&password=PASSWORD&client_id=XXXXX&client_secret=XXXXXXXXXXX

**Comment by daohoangson** [comment]
That looks good, make sure you were making a POST request instead of a normal http GET.

**Comment by SomeRandomDude32** [comment]
Would you be able to explain the client secret and client iD?

Where can I set the client secret on Xenforo2, there isn't an option in the Add-on setting

What value would be put in the client is? Their index like 1,2etc? And if so where can I find that 

Also would you be able to explain your previous response a little bit more? I think this thread will be able to help beginners.

**Comment by daohoangson** [comment]
The client id/secret are generated when you create the client.

To create a client, go to http://domain.com/account/api. You may need to grant the user group permission before you are able to access that page though.

**Comment by TitanX101** [comment]
Hi Im trying to use https://github.com/BerkanYildiz/XenForo.NET to authenticate, my code looks like:

public const string Url                 = "https://localhost/xenforo/api/";
public const string ClientId          = "hpoZ2pLosC";
public const string ClientSecret   = "4rhLxxvWkNrfh96";

But I didn't get any answer... Can pls tell me what I'm doing wrong?

Edit: Also I'm using this url localhost/xenforo/api/index.php?oauth/token&client_id=hpoZ2pLosC&client_secret=4rhLxxvWkNrfh96&grant_type=password&username=User&password=pass

**Comment by daohoangson** [comment]
You probably need to ask that library author.
