### ISSUE TITLE
Forum Model Missing Parent Category

### ISSUE THREAD

**Issue by fsosa** [xfrocks/bdApi#47]
Hi!

Currently, the forum API does not contain the parent category. I made a minor patch to add a new property, but was wondering if you would consider it. 

In  `prepareApiDataForForum` in `bdApi_Extend_Model_Forum`, I added the following:

```
$data['category'] = array(
    'parent_category_id' => $forum['parent_node_id']
);
```

Ideally, I'd like to also add more information from the parent category, such as the category description, but I'm not sure how to do that.

**Comment by daohoangson** [comment]
Normally we put the parent id in navigation element (GET `/navigation`) for... navigation need. What is your use case here?

**Comment by fsosa** [comment]
I'm so sorry, you're completely right. This is exactly for navigation purposes and I didn't read the docs thoroughly enough to see there's an API exactly for this. My bad. I appreciate your help!
