### ISSUE TITLE
POST /oauth/token/google broken

### ISSUE THREAD

**Issue by codeversed** [xfrocks/bdApi#5]
Regarding this chunk of code: 
https://github.com/xfrocks/bdApi/blob/343af19553cbc9da6b767680c8ece22f04c50f4b/xenforo/library/bdApi/ControllerApi/OAuth.php#L199-L206

Since the API has been written, Google has moved away form authenticating with only Google+ and now uses a more generic sign-in authentication, See here: https://developers.google.com/identity/sign-in/android/backend-auth

**Comment by daohoangson** [comment]
Thank you Steve, PR soon?

**Comment by daohoangson** [comment]
Any news regarding this @codeversed?

**Comment by daohoangson** [comment]
This has been fixed via b5b8fc5.
