### ISSUE TITLE
Some help with getting user information.

### ISSUE THREAD

**Issue by AdriaanBoshoff** [xfrocks/bdApi#57]
Hi, I'm having a really hard time reading the documentation and understanding it in general. I have looked at your script.php example but I'm still unsure since I don't know php.

I want to get the users information like groups and etc. The only issue with that is I'm unsure as to how I can do so. My understanding is is that I need to get the access token and then use that to get the user information. Now my question is. How should the URL look like to get the access token and how should the URL look like to get the user information?

**Comment by daohoangson** [comment]
You need to use OAuth 2 to get the token, the URL is http://domain.com/xenforo/api/index.php?oauth/authorize.

Then you should be able get current user info at http://domain.com/xenforo/api/index.php?users/me&oauth_token=xxx

**Comment by AdriaanBoshoff** [comment]
Hi, thanks for the help. How can I get the user id? My plan is to make a login system for my application where they just need to enter their username and password. Sorry for the noob questions.

**Comment by daohoangson** [comment]
After you complete the OAuth flow, the user_id will be returned together with the new token.

Or you can get the current user_id by requesting `users/me` with a valid token.

**Comment by AdriaanBoshoff** [comment]
Thats the thing. When I go there it gives me this: https://i.imgur.com/YxtOus2.png What paramaters am I missing?

EDIT: I'm using xenforo v2.0.7

**Comment by daohoangson** [comment]
Which OAuth2 library are you using to authenticate? Looks like the URL doesn't have enough parameters.

**Comment by AdriaanBoshoff** [comment]
I'm using this: https://github.com/stievie/POAuth2

There was a spelling mistake in my code from before.

This is the new response I'm getting now:
```
Error: Server returned 404: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
<script src="/cdn-cgi/apps/head/J97EOV9Gzn6qyYz03XpabAmiPlg.js"></script></head><body>
<h1>Not Found</h1>
<p>The requested URL /token was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```
My Code:
```
procedure TMainForm.Button2Click(Sender: TObject);
var
  res: TOAuth2Response;
begin
  FOAuthClient.Site := 'https://quantumsoftware.co.za';
  FOAuthClient.GrantType := gtPassword;
  FOAuthClient.UserName := 'TestAcc';
  FOAuthClient.PassWord := 'TestPass';
  try
    res := FOAuthClient.Get('/api/index.php?oauth/authorize');
    txtAccessToken.Text := FOAuthClient.AccessToken.AccessToken;
    txtRefreshToken.Text := FOAuthClient.AccessToken.RefreshToken;
    txtExpires.Text := IntToStr(FOAuthClient.AccessToken.ExpiresIn);
    txtResponse.Lines.Clear;
    if res.Code = HTTP_OK then begin
      if IsJson(res.ContentType) then begin
        with TJson.Create do try
          Parse(res.Body);
          Print(txtResponse.Lines);
        finally
          Free;
        end;
      end else begin
        txtResponse.Text := res.Body;
      end;
    end else begin
      txtResponse.Text := Format('Error (%d): %s', [res.Code, res.Body]);
    end;
  except
    on E: Exception do
      txtResponse.Text := Format('Error: %s', [E.Message]);
  end;
end;
```

Might it just be the library thats faulty? Note I've never worked with oauth2 before so this is a little new to me.

**Comment by daohoangson** [comment]
Ah, long time no see Delphi code.

I believe this library will handle the token fetching by itself so you just need configure username, password + client_id/secret then request the resource as needed (`/users/me` for example).

The error you were getting (`/token was not found on this server`) may be an issue with the library config. I checked their code and they are using `/token` as `TOAuth2Config.TokenEndPoint`. I'm not that familiar with this library but you have to change this to `/api/index.php?oauth/token` for it to work.

If the library doesn't allow you to do that, you can use url rewrite on your web server (Apache / Nginx) to route `/token` to `/api/index.php?oauth/token`.

**Comment by AdriaanBoshoff** [comment]
I see. Thanks for all your help. I think I understand now. I can't use URL rewrite as I'm on shared hosting and they don't seem to provide me access to that. But I have found this: https://github.com/stievie/POAuth2/blob/master/uOAuth2Consts.pas I believe I can just edit this and see if I can get it to work.

**Comment by AdriaanBoshoff** [comment]
I seem to have figured out this library but the issue is that the server seems to return the data in txt/html and it then doesn't want to give the full output of the data returned by the server.

Is it possible that you can write me a small php script that allows me to post the username and password and then return the token. 

I can't get this lib to work and I can't seem to find a working lib.

**Comment by daohoangson** [comment]
For a complete example in PHP to login with username+password and get user info, see this https://gist.githubusercontent.com/daohoangson/b37d069bc0902b29b8295e555dac9351/raw/b8bbafdfc882cc75c3dac24af6c887a9125fc2e1/script.php

**Comment by AdriaanBoshoff** [comment]
Thanks

**Comment by AdriaanBoshoff** [comment]
Hi, I'm unsure if this is possible but I did the following.

I downloaded your script.php and add the following at the top:
```
$username = $_GET["username"];
$password = $_GET["password"];
```

I then changed `define('API_SCRIPT_ROOT', 'https://xfrocks.com/api');` to the correct info.

I then saved this as oauth.php and uploaded it to my web server. But when i try to do a post request to it using the correct username and password I get the following response:

`Please authenticate with a valid username and password.`

**Comment by daohoangson** [comment]
Have you updated `API_SCRIPT_CLIENT_ID` and `API_SCRIPT_CLIENT_SECRET` with the client key/secret for your site?

**Comment by AdriaanBoshoff** [comment]
Thats the thing. Where can I get that? I basically only want to send the username and password because I'm making a login system for my app.

**Comment by daohoangson** [comment]
Oh, you have to create the client. Go to http://domain.com/xenforo/account/api, you may need to allow the user group permission "[bd] API: Create Client" before you can access that page.
