### ISSUE TITLE
POST grant Password Not working

### ISSUE THREAD

**Issue by Shizuko** [xfrocks/bdApi#64]
Hello Folks,

first thanks for this project it is really good,
anyway i am Using the Post Grant Password function
like this : 

http://website.net/api/index.php?oauth/token&

POST /api/index.php?oauth/token& HTTP/1.0
Host: website.net
Content-Type: application/x-www-form-urlencoded
Content-Length: 113

grant%5Ftype=password&client%5Fid=xxxxxx&client%5Fsecret=xxxxxxx%5Fsecret&username=xxxxx&password=xxxxxx

this is the response I get :

HTTP/1.1 401 Unauthorized
Date: Wed, 15 Aug 2018 01:45:10 GMT
Server: Apache/2.4.33 (Win64) PHP/5.6.35
X-Powered-By: PHP/5.6.35
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Last-Modified: Wed, 15 Aug 2018 01:45:10 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: private, no-cache, max-age=0
Set-Cookie: xf_session=wzZmA9s_-oA6pDuwjJe8ggXI_JTqy5m8; path=/; httponly
Content-Length: 65
Connection: close
Content-Type: application/json; charset=utf-8

{"status":"error","errors":["bdapi_oauth2_error_invalid_client"]}

Any idea what is going on ?

Thanks .

**Comment by daohoangson** [comment]
Which version of XenForo / Api are you using?

Also, the error indicates that you have sent an invalid client key/secret combination. Maybe double check that?

Also, you may need to install the add-on again because the phrase is missing.

**Comment by Shizuko** [comment]
since i am using this with my own app i can send whatever i choose as api key and secret no?
(hope i am not saying something very stupid)

**Comment by daohoangson** [comment]
Oh no, you need to install the api on XF then go to http://domain.com/index.php?account/api to generate a client.

**Comment by Shizuko** [comment]
didn't know about that! any way i did generate a client and use the correct client key and secret
and i am still getting the same error :(

**Comment by daohoangson** [comment]
Which version of XenForo / Api are you using?

**Comment by Shizuko** [comment]
Xenforo 2.0.9

as for the api i tried with both the 2.0.0 alpha 2 and the last version on Github

this is the message with alpha 2 version :  

HTTP/1.1 401 Unauthorized
Date: Wed, 15 Aug 2018 02:44:16 GMT
Server: Apache/2.4.33 (Win64) PHP/5.6.35
X-Powered-By: PHP/5.6.35
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Last-Modified: Wed, 15 Aug 2018 02:44:16 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: private, no-cache, max-age=0
Set-Cookie: xf_session=sjKE17nizkRusgkUo5uivCZzMX5zKJMB; path=/; httponly
Content-Length: 61
Connection: close
Content-Type: application/json; charset=utf-8

{"status":"error","errors":["Client authentication failed."]}

**Comment by Shizuko** [comment]
it was an extra space that ruined it
anyway thanks a lot for your help
now it works thanks to your tips

**Comment by daohoangson** [comment]
Awesome.
