### ISSUE TITLE
Find users by email address without requiring admincp scope

### ISSUE THREAD

**Issue by mjaschen** [xfrocks/bdApi#7]
I'm building an application for our site where users can signup with much simpler user interface compared to XenForo's registration page (only three form fields for username, email address, and password).

I'm checking the availability of username and email address by asking the API with a `GET /users/find` request.

Search by email address is [only allowed for users within the _admincp_ scope](https://github.com/xfrocks/bdApi/blob/master/xenforo/library/bdApi/ControllerApi/User.php#L73) (`bdApi_Model_OAuth2::SCOPE_MANAGE_SYSTEM`). 

I'm wondering if there's a way to enable searching by email address by a less privileged permission, maybe be adding another oAuth scope or something. It's clear, that search by email address shouldn't be allowed for users with the simple `read` permission for privacy reasons but on the other side I don't want grant the signup application admin permissions.

Has anyone thoughts on that?

**Comment by daohoangson** [comment]
For registration, maybe you can issue the POST `/users` request and catch the error from there?

**Comment by mjaschen** [comment]
That's exactly what I'm doing right now, but I want to achieve something different: I want to show the availability of an email address for registration immediately when the user has entered it into the signup form (the form field change event triggers an Ajax request, the server-side application requests `/users/find` and responds success/failure information back to the browser).

So the username availability can be checked before submitting the form, the email address availability unfortunately not.

**Comment by JulianD** [comment]
I'm not on a computer right now to test this but when a post request fails, do the api returns just one error or several ones? Because if the api returns all the errors found,  you can send a post request with a field which will surely fail (for example an empty password) and check to see if it contains an error for the email field.

**Comment by mjaschen** [comment]
@JulianD Thanks, that's a good idea. I'll verify if it works.

**Comment by mjaschen** [comment]
@JulianD Your suggestion works!

When sending just the email address in the `POST /users` request the API reponds with

``` json
{"errors":{"email":"Email addresses must be unique. The specified email address is already in use.","username":"Please enter a name that is at least 3 characters long."}
```

So it's possible to check for the `email` key in the `errors` object.

Thanks again!
