### ISSUE TITLE
AUthentification OK even with password wrong

### ISSUE THREAD

**Issue by Shizuko** [xfrocks/bdApi#71]
Hello,

so i ran some tests and i found out that when you Use the grant password function the account will be authentified whatever password you use
you just have to make sure that the client key and client secret are correct

is it supposed to work that way ?

Best Regards,

**Comment by daohoangson** [comment]
No, the password must matches the username.

How are you testing it? Also, which version are you testing against?

**Comment by Shizuko** [comment]
Hello,
i am using your public version :   2.0.0 Alpha 4

and i confirm again that with "**grant password**" as long as you have **client key** and **client secret** and **username**, any password will work
returning this

`HTTP/1.1 200 OK
Date: Wed, 22 Aug 2018 12:40:36 GMT
Server: Apache/2.4.33 (Win64) PHP/7.2.4
X-Powered-By: PHP/7.2.4
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Last-Modified: Wed, 22 Aug 2018 12:40:36 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: private, no-cache, max-age=0
Set-Cookie: xf_session=A7YR_UrWdi0kkdS_KbqmLTF-PGP1Of8M; path=/; HttpOnly
Content-Length: 160
Connection: close
Content-Type: application/json; charset=utf-8

{"access_token":"ZcNdDeZ8RuYSRqRqw5wrzBU8L3kXxJNuVWkS43lS","token_type":"Bearer","expires_in":"3600","refresh_token":"QoiyMu4vlOdFE2QOhjb8RT7OO13vmnI6ZyeFZ8CF"} `

**Comment by daohoangson** [comment]
Hmm, is your server public? Can I test it? Have just run this against our dev server...

```
curl http://xenforo2.local.xfrocks.com:20080/api/index.php\?oauth/token -d 'grant_type=password&client_id=test&client_secret=test&username=user1&password=wrong'
{"status":"error","errors":["Incorrect password. Please try again."],"system_info":{"debug_url":"http:\/\/xenforo2.local.xfrocks.com:20080\/api\/index.php?oauth\/token&_debug=1"}}%
```

The client id/secret is correct, this works:

```
curl http://xenforo2.local.xfrocks.com:20080/api/index.php\?oauth/token -d 'grant_type=password&client_id=test&client_secret=test&username=user1&password=123456'
{"access_token":"59tISYgN3AxGTXlwAmILpuku59OxVZ8Xh6nD8fxe","token_type":"Bearer","expires_in":"3600","refresh_token":"BrFFtXijmxeMuFf6TWkGr2WSSB1vf8NbKS2Giihi","scope":"read post usercp conversate","system_info":{"debug_url":"http:\/\/xenforo2.local.xfrocks.com:20080\/api\/index.php?oauth\/token&_debug=1"}}%
```

**Comment by Shizuko** [comment]
a correction , i was using the alpha 2 version somehow

updating to alpha 4 solved the problem
thank you for your help
