### ISSUE TITLE
Thread Prefix

### ISSUE THREAD

**Issue by Alehap** [xfrocks/bdApi#8]
Hello,
The first I wanna say thanks to developer, bdApi so good for Xenforo.
But I've a trouble with Thread Prefix, how can I create a Thread with the Prefix?

Thanks too much!

**Comment by daohoangson** [comment]
Currently there is no support at all for the prefix system. Willing to do a PR? :wink:

**Comment by Alehap** [comment]
Oh Plugin này của người Việt viết ak :3 :+1: 
Mình tính dùng cURL để post nhưng thấy có plugin API rồi nên mới chuyển wa dùng plugin luôn.
Mình đang định viết script để leech bài về forum :3
